export const metadata = {
  title: "PortFolio - Olmos",
  description: "Generated by Next.js",
};

import Navbar from "../components/Navbar/Navbar";
import "../styles/globals.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar></Navbar>
        {children}
      </body>
    </html>
  );
}
