export const metadata = {
  title: "PortFolio - Olmos",
  description: "Generated by Next.js",
};

import Navbar from "../components/Navbar/Navbar";
import { TabBar } from "@/components";
import "../styles/globals.css";
import { lato } from "../app/fonts";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <Navbar></Navbar>
        {children}
        <TabBar></TabBar>
      </body>
    </html>
  );
}
